[project]
name = "auth-service"
version = "0.1.0"
description = "Python Boilerplate Authentication Microservice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.1.0",
]
