name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    working-directory: auth-service

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: astral-sh/setup-uv@v5
    - uses: actions/setup-python@v5
    - run: uv sync --all-extras --dev
    - uses: pre-commit/action@v3.0.1
